### ISSUE TITLE
[Feature Request] - add pseudolocalization

### ISSUE THREAD

**Issue by havi05** [VP-GAMES/Godot4LocalizationEditor#1]
Maybe you can add a button to toggle pseudolocalization with the first (or with a selected) language.
If there is enough space the pseudolocalization options could be added as well.
It would be great if this would work in the editor but if not it should work on runtime.

Currently there is only this documentation:
https://github.com/godotengine/godot-docs/pull/5119/files

I'm glad it works with Godot 4.

**Comment by VP-GAMES** [comment]
Done with work on pseudolocalization. Please see version 0.2.5 => https://github.com/VP-GAMES/Godot4LocalizationEditor/commit/e6fc4f3ebacacde11c6b763b750af62dd8dbbbb9
