### ISSUE TITLE
Cannot remove Locales.

### ISSUE THREAD

**Issue by CantyCanadian** [VP-GAMES/Godot4LocalizationEditor#12]
Gives an error whenever you remove a locale.

![image](https://github.com/VP-GAMES/Godot4LocalizationEditor/assets/7960042/fc47aadb-43d6-47be-90ca-0e575b4618cb)

**Comment by AmploDev** [comment]
@CantyCanadian I created a fork to fix this issue. You can also do it manually by editing:
/addons/localization_editor/scenes/locales/LocalizationLocale.gd line 57 by changing cancelled into canceled

EDIT: This still does not save any translations. So unfortunately this does not work yet

**Comment by VP-GAMES** [comment]
Fix this with this commit: https://github.com/VP-GAMES/Godot4LocalizationEditor/commit/a85f6c02ea7de0c68d75f4160fb8666665ee7b1f
