### ISSUE TITLE
plugin not working. 

### ISSUE THREAD

**Issue by Mrunbelievable** [VP-GAMES/Godot4LocalizationEditor#13]
![WechatIMG196](https://github.com/VP-GAMES/Godot4LocalizationEditor/assets/16590364/5b4088ab-9e74-48ee-a032-01772fb18605)

**Comment by Mrunbelievable** [comment]
I have alredy reload the project, still keeps empty after I click Localizaiton

**Comment by VP-GAMES** [comment]
Please give me some more information. Do you install it from store or from github? What is your used Godot version 4.+?
Please try to use godot 4.2+
