### ISSUE TITLE
[Feature Request] - Changing the translation service

### ISSUE THREAD

**Issue by SIBtomcat** [VP-GAMES/Godot4LocalizationEditor#4]
Is it possible to add the ability to change the translator (for example on [DeepL](https://www.deepl.com/translator))?

**Comment by VP-GAMES** [comment]
It's possible. I used google. Google is free and has no limitations in word count and so. But it really simple to integrate new apis like DeepL. U have to change only one method/function.

**Comment by SIBtomcat** [comment]
The translation quality at DeepL is much better. Although the number of supported languages is still less. It is possible to translate a sufficient number of words for free. There is a free subscription which extends the features.

**Comment by VP-GAMES** [comment]
I implemented support for DeepL on my local machine, but i can not test it. You need credit card for registration. I have no credit card and a fake one(generated) not working. In a feature i can test  implementation if i have a real registration and a DeepL-Auth-Key. U can see it here => [Example](https://www.deepl.com/docs-api)

**Comment by VP-GAMES** [comment]
I implemented DeepL local on my machine. But i can not test it. To test API you need your credit card. I have no credit card and a fake one(generated) not working. I can add support for DeepL in a future, if I get DeepL-Auth-Key.
You can read it here: [Example](https://www.deepl.com/docs-api)

**Comment by SIBtomcat** [comment]
Yep, that's the problem… the thing is, I can't check now — the country I'm in is under sanctions and local bank cards are not accepted anywhere… It's my fault — I was sure that a free account, can be opened without a credit card. I should have checked that right away. But, hopefully, the problem will be solved in time. If things settle down, the possibility of a good translation will be in high demand. Huge thanks! Огромная Благодарность! Bardzo dziękuję!

**Comment by VP-GAMES** [comment]
No problem, if i have a change to use credit card i do this. Нет проблем. Если я смогу воспользоватся своей кредиткой сделаю это.

**Comment by VP-GAMES** [comment]
In new commit I prepare implementation for Yandex and DeepL translators: https://github.com/VP-GAMES/Godot4LocalizationEditor/commit/507902e11c9f0f1c3bf6264c1615d251f8c5239b

**Comment by VP-GAMES** [comment]
Add support for DeepL translator: https://github.com/VP-GAMES/Godot4LocalizationEditor/commit/202814a79ae98904372007ecc7a9839d297dc798
